version: '3.3'
services:
    swagger-ui:
        ports:
            - '8081:8080'
        environment:
            - SWAGGER_JSON=/mnt/EmVera-BUENA-0.1.9-swagger.json
        volumes:
            - '~/dist:/mnt'
        image: swaggerapi/swagger-ui
    timescaledb:
        container_name: timescaledb
        ports:
            - '127.0.0.1:5432:5432'
        environment:
            - POSTGRES_PASSWORD=password
        image: 'timescale/timescaledb:latest-pg12'

    iot-api:
        network_mode: host
        image: jmeverac/iot-api:latest
